FROM buildpack-deps:trixie

LABEL org.opencontainers.image.authors="batleforc"
LABEL org.opencontainers.image.url="https://github.com/batleforc/WeeboDevImage/che-min"
LABEL org.opencontainers.image.source="https://github.com/batleforc/WeeboDevImage"
LABEL org.opencontainers.image.title="Che-MinImage"

ENV KUBE_VERSION="v1.35.1"
ENV NVM_VERSION="v0.40.4"
ENV NODE_VERSION="24.13.0"

ENV HOME=/home/tooling
ENV NVM_DIR=/home/tooling/.nvm

ENV GLOBALS_FOLDER="/globals/"
ENV GLOBALS_BASHRC="${GLOBALS_FOLDER}bashrc"

RUN mkdir -p ${GLOBALS_FOLDER} && touch ${GLOBALS_BASHRC}
RUN echo 'source /globals/bashrc' >> ${HOME}/.bashrc

# Add auto-completion

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends bash-completion libc6 locales locales-all && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /home/tooling/ && \
    echo "source /etc/profile.d/bash_completion.sh" >> ${GLOBALS_BASHRC} && \
    locale-gen "en_US.UTF-8" && \
    dpkg-reconfigure locales

## Install Kubectl
RUN curl -fsSLo /usr/local/bin/kubectl \
    https://dl.k8s.io/release/${KUBE_VERSION}/bin/linux/amd64/kubectl && \
    chmod +x /usr/local/bin/kubectl && \
    kubectl completion bash > /etc/bash_completion.d/kubectl && \
    echo 'source /etc/bash_completion.d/kubectl' >> ${GLOBALS_BASHRC}

ENV KUBECONFIG=/home/user/.kube/config
ENV LANG="en_US.UTF-8"

## Install NodeJS
SHELL ["/bin/bash", "-lc"]
RUN curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/${NVM_VERSION}/install.sh | bash && \
    { \
    echo 'export NVM_DIR="/home/tooling/.nvm"'; \
    echo '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"'; \
    echo '[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"'; \
    } >> ${GLOBALS_BASHRC} && \
    . ${GLOBALS_BASHRC} && \
    nvm install ${NODE_VERSION} && \
    nvm alias default ${NODE_VERSION} && \
    nvm use default && \
    nvm cache clear && \
    npm install --global yarn && \
    corepack enable pnpm
ENV VSCODE_NODEJS_RUNTIME_DIR=/home/tooling/.nvm/versions/node/v${NODE_VERSION}/bin
ENV PATH=/home/tooling/.nvm/versions/node/v${NODE_VERSION}/bin:$PATH


## https://github.com/devfile/developer-images/blob/main/universal/ubi8/entrypoint.sh

RUN mkdir -p /home/tooling/.local/bin && \
    chgrp -R 0 /home && chmod -R g=u /home && \
    useradd -u 1234 -G root -d /home/user --shell /bin/bash -m user
ENV PATH="/home/user/.local/bin:$PATH"
ENV PATH="/home/tooling/.local/bin:$PATH"

COPY --chown=0:0 .copy-files /home/tooling/

## Try a fix for path not found

RUN echo 'export PATH="/home/tooling/.local/bin:$PATH"' >> ${GLOBALS_BASHRC}
RUN echo 'export PATH="/home/user/.local/bin:$PATH"' >> ${GLOBALS_BASHRC}

## Fix uv_os_get_passwd

RUN chmod g=u /etc/passwd /etc/group

USER 1234

