policies:
- name: Upgrade Min Space
  config:
  - ./0.updatecli/min-space.yaml
  values:
  - ./0.updatecli/values.yaml
- name: Upgrade Base Space
  config:
  - ./0.updatecli/base-space.yaml
  values:
  - ./0.updatecli/values.yaml
- name: Upgrade Go Space
  config:
  - ./0.updatecli/go-space.yaml
  values:
  - ./0.updatecli/values.yaml
- name: Upgrade Rust Space
  config:
  - ./0.updatecli/rust-space.yaml
  values:
  - ./0.updatecli/values.yaml
- name: Upgrade Ops Space
  config:
  - ./0.updatecli/ops-space.yaml
  values:
  - ./0.updatecli/values.yaml
- name: Upgrade Browser Space
  config:
  - ./0.updatecli/browser-space.yaml
  values:
  - ./0.updatecli/values.yaml
