FROM ghcr.io/batleforc/weebodevimage/che-base:main

LABEL org.opencontainers.image.url="batleforc/che-rust"
LABEL org.opencontainers.image.title="Che-RustImage"
LABEL org.opencontainers.image.source = "https://github.com/batleforc/WeeboDevImage"

ENV HOME=/home/tooling
USER 0

# START Infra Block

ENV RUSTUP_HOME=/home/tooling/.rustup \
    CARGO_HOME=/home/tooling/.cargo  \
    PATH=/home/tooling/.cargo/bin:$PATH \
    RUST_VERSION=1.80.0

RUN set -eux; \
    dpkgArch="$(dpkg --print-architecture)"; \
    case "${dpkgArch##*-}" in \
    amd64) rustArch='x86_64-unknown-linux-gnu'; rustupSha256='0b2f6c8f85a3d02fde2efc0ced4657869d73fccfce59defb4e8d29233116e6db' ;; \
    armhf) rustArch='armv7-unknown-linux-gnueabihf'; rustupSha256='f21c44b01678c645d8fbba1e55e4180a01ac5af2d38bcbd14aa665e0d96ed69a' ;; \
    arm64) rustArch='aarch64-unknown-linux-gnu'; rustupSha256='673e336c81c65e6b16dcdede33f4cc9ed0f08bde1dbe7a935f113605292dc800' ;; \
    i386) rustArch='i686-unknown-linux-gnu'; rustupSha256='e7b0f47557c1afcd86939b118cbcf7fb95a5d1d917bdd355157b63ca00fc4333' ;; \
    *) echo >&2 "unsupported architecture: ${dpkgArch}"; exit 1 ;; \
    esac; \
    url="https://static.rust-lang.org/rustup/archive/1.26.0/${rustArch}/rustup-init"; \
    wget "$url"; \
    echo "${rustupSha256} *rustup-init" | sha256sum -c -; \
    chmod +x rustup-init; \
    ./rustup-init -y --no-modify-path --profile minimal --default-toolchain $RUST_VERSION --default-host ${rustArch}; \
    rm rustup-init; \
    chmod -R a+w $RUSTUP_HOME $CARGO_HOME; \
    rustup --version; \
    cargo --version; \
    rustc --version; \
    rustup completions bash > /etc/bash_completion.d/rustup && \
    echo 'source /etc/bash_completion.d/rustup' >> ${HOME}/.bashrc && \
    rustup completions bash cargo > /etc/bash_completion.d/cargo && \
    echo 'source /etc/bash_completion.d/cargo' >> ${HOME}/.bashrc

RUN echo 'export RUSTUP_HOME=/home/user/.rustup' >> ${HOME}/.bashrc
RUN echo 'export CARGO_HOME=/home/user/.cargo' >> ${HOME}/.bashrc
RUN echo 'export PATH=/home/user/.cargo/bin:$PATH' >> ${HOME}/.bashrc


# END Infra Block

ENV STAR_NO="true"

# START User Block

RUN set -eux; \
    rustup component add clippy; \
    rustup component add rustfmt;\
    cargo install --locked cargo-audit; \
    cargo install --locked cocogitto; \
    rustup target add wasm32-unknown-unknown;

# START User Block
USER 1234
ENV HOME=/home/user
RUN stow . -t /home/user -d /home/tooling --no-folding
RUN cp -f /home/tooling/.bashrc /home/user/.bashrc
WORKDIR /home/user
ENTRYPOINT [ "/entrypoint.sh" ]
CMD ["tail", "-f", "/dev/null"]