FROM ghcr.io/batleforc/weebodevimage/che-base:main

LABEL org.opencontainers.image.url="batleforc/che-golang"
LABEL org.opencontainers.image.title="Che-GolangImage"
LABEL org.opencontainers.image.source="https://github.com/batleforc/WeeboDevImage"

ENV HOME=/home/tooling
USER 0

# START Infra Block

RUN curl https://mise.run | sh && \
    echo 'eval "$(~/.local/bin/mise activate bash)"' >> ${GLOBALS_BASHRC}

# END Infra Block

ENV STAR_NO="true"

# START User Block


# START User Block
USER 1234
ENV HOME=/home/user
RUN stow . -t /home/user -d /home/tooling --no-folding
RUN cp -f /home/tooling/.bashrc /home/user/.bashrc
WORKDIR /home/user
ENTRYPOINT [ "/entrypoint.sh" ]
CMD ["tail", "-f", "/dev/null"]