FROM alpine/curl:latest

LABEL org.opencontainers.image.authors="batleforc"
LABEL org.opencontainers.image.url="{{.Repo}}alpine-jqcurl"
LABEL org.opencontainers.image.title="Alpine-jqcurl"

# Install jq
RUN apk add --no-cache jq