FROM linuxserver/wireguard:latest

LABEL org.opencontainers.image.authors="batleforc"
LABEL org.opencontainers.image.url="{{.Repo}}wireguard"
LABEL org.opencontainers.image.title="Wireguard"

WORKDIR /app

# Install Wireguard REST API
COPY install.sh /app
RUN chmod +x install.sh

ENTRYPOINT [ "/app/install.sh" ]