FROM linuxserver/wireguard:latest

LABEL org.opencontainers.image.authors="batleforc"
LABEL org.opencontainers.image.url="{{.Repo}}wireguard"
LABEL org.opencontainers.image.title="Wireguard"

WORKDIR /app

# Install Wireguard REST API
RUN wget https://github.com/FokiDoki/WireRest/releases/download/0.7-BETA/wirerest-0.7.jar && apk add --no-cache openjdk21

COPY ./root /